void breakfast_meal(int consumption);
void cinnamon();
void onion();
void vanilla();
void scramble();
void feta_omelet();
void banana_pancakes();
void banana();
void vegan();
void breakfast_quesadillas();
void mealplan();